import { useEffect, useState } from 'react';
import './admin-login.css';
const base=import.meta.env.VITE_API_BASE_URL??'https://api.monpetitvoyageur.com';
export default function AdminLogin({onLogin}:{onLogin:(email:string,password:string)=>Promise<void>}){
 const [token]=useState(()=>new URLSearchParams(location.hash.slice(1)).get('reset')||'');
 const [mode,setMode]=useState<'login'|'forgot'|'reset'>(token?'reset':'login');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{if(token)history.replaceState(null,'',location.pathname+location.search);},[token]);
 function change(next:'login'|'forgot'){setMode(next);setError('');setMessage('');setPassword('');setConfirm('');}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setMessage('');setBusy(true);try{
   if(mode==='login'){await onLogin(email,password);return;}
   if(mode==='reset'&&password!==confirm)throw new Error('Les deux mots de passe ne correspondent pas.');
   const r=await fetch(base+'/api/admin/'+(mode==='forgot'?'forgot-password':'reset-password'),{method:'POST',headers:{'Content-Type':'application/json'},credentials:'omit',body:JSON.stringify(mode==='forgot'?{email}:{token,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Une erreur est survenue. Réessayez.');setMessage(d.message);if(mode==='reset'){setMode('login');setPassword('');setConfirm('');}
 }catch(e){setError(e instanceof TypeError?'Connexion au serveur impossible. Vérifiez votre connexion puis réessayez.':(e as Error).message);}finally{setBusy(false);}}
 return <main className="access-page"><section className="access-brand"><a href="https://www.monpetitvoyageur.com" className="access-logo"><img src="/logo.jpeg" alt="Mon Petit Voyageur" /><div><span>Administration</span><small>ESPACE PRIVÉ</small></div></a><div className="access-intro"><span className="access-overline">LES VOYAGES, VUS D’ENSEMBLE</span><h1>Tout commence<br/>par une belle<br/><em>perspective.</em></h1><p>Votre activité, vos voyageurs et vos abonnements.<br/>Réunis dans votre espace personnel.</p><div className="access-topics"><span>Utilisateurs</span><span>Abonnements</span><span>Voyages</span></div></div><div className="access-bottom"><span className="access-lock">◇</span> Un espace réservé à votre administration <span>01 — MPV</span></div></section><section className="access-form-side"><div className="access-top-label"><span/> ACCÈS PRIVÉ</div><div className="access-form-wrap"><img className="access-symbol access-symbol-logo" src="/logo.jpeg" alt="Mon Petit Voyageur" /><p className="access-overline">MON PETIT VOYAGEUR</p><h2>{mode==='login'?'Bon retour.':mode==='forgot'?'Un nouveau départ.':'Votre nouvel accès.'}</h2><p className="access-description">{mode==='login'?'Connectez-vous pour retrouver votre tableau de bord.':mode==='forgot'?'Indiquez votre adresse email pour recevoir un lien de réinitialisation.':'Choisissez un nouveau mot de passe pour votre administration.'}</p>{error&&<p role="alert" className="access-alert">{error}</p>}{message&&<p role="status" className="access-success">{message}</p>}<form onSubmit={submit}>
 {mode!=='reset'&&<label className="access-label">Adresse email<input type="email" autoComplete="username" placeholder="vous@exemple.com" required value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label>}
 {mode!=='forgot'&&<><div className="access-password-label"><label htmlFor="admin-password">{mode==='reset'?'Nouveau mot de passe':'Mot de passe'}</label>{mode==='login'&&<button type="button" onClick={()=>change('forgot')}>Mot de passe oublié ?</button>}</div><div className="access-password"><input id="admin-password" type={visible?'text':'password'} autoComplete={mode==='reset'?'new-password':'current-password'} placeholder={mode==='reset'?'12 caractères minimum':'Votre mot de passe'} minLength={mode==='reset'?12:undefined} required value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/><button type="button" aria-label={visible?'Masquer le mot de passe':'Afficher le mot de passe'} aria-pressed={visible} onClick={()=>setVisible(!visible)}>{visible?'Masquer':'Voir'}</button></div></>}
 {mode==='reset'&&<label className="access-label">Confirmer le mot de passe<input required minLength={12} type={visible?'text':'password'} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} disabled={busy}/></label>}
 <button className="access-submit" disabled={busy}>{busy?'Un instant…':mode==='login'?'Accéder à mon espace':mode==='forgot'?'Recevoir le lien':'Enregistrer mon mot de passe'}<span aria-hidden="true">→</span></button></form>
 {mode!=='login'?<button className="access-back" onClick={()=>change('login')}>← Revenir à la connexion</button>:<p className="access-session">Session sécurisée · Déconnexion après 30 minutes</p>}
 </div><footer className="access-footer"><span>© {new Date().getFullYear()} Mon Petit Voyageur</span><a href="https://www.monpetitvoyageur.com">Voir le site voyageur ↗</a></footer></section></main>;
}
