import { useEffect, useState } from 'react';
import './admin.css';
import AdminLogin from './AdminLogin';

const base = import.meta.env.VITE_API_BASE_URL ?? 'https://api.monpetitvoyageur.com';
let adminToken='';
const api={
 login:async(body:{email:string;password:string})=>{const r=await fetch(base+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'omit',body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Connexion impossible');adminToken=d.token;},
 logout:async()=>{adminToken='';}
};
async function get(path: string) { if(!adminToken)throw new Error('Connectez-vous pour accéder à l’administration.'); const r=await fetch(base+path,{headers:{Authorization:'Bearer '+adminToken},credentials:'omit'}); const data=await r.json(); if(!r.ok) throw new Error(data.error || 'Service indisponible'); return data; }
const date=(s:string)=>s ? new Date(s.includes('T')?s:s.replace(' ','T')+'Z').toLocaleDateString('fr-FR'):'—';
const statuses:Record<string,string>={active:'Actif',trialing:'Essai',past_due:'Impayé',canceled:'Annulé',none:'Sans abonnement',paid:'Payée',open:'À payer',draft:'Brouillon',void:'Annulée',uncollectible:'Irrécouvrable'};
const money=(n:number,c='eur')=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:c.toUpperCase()}).format(n/100);
const tabs=['Vue d’ensemble','Utilisateurs','Abonnements','Clics & trafic','Revenus','Voyages','Connexions'];
export default function LiveAdmin(){
 const [tab,setTab]=useState(tabs[0]),[days,setDays]=useState('30'),[q,setQ]=useState(''),[status,setStatus]=useState(''),[data,setData]=useState<any>(null),[payments,setPayments]=useState<any>(null),[error,setError]=useState(''),[paymentError,setPaymentError]=useState(''),[busy,setBusy]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 async function load(){setBusy(true);setError('');try{setData(await get('/api/admin/dashboard?days='+days));}catch(e){setData(null);setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[days]);
 useEffect(()=>{setPayments(null);setPaymentError('');if(tab==='Revenus'&&data?.sources.stripe)get('/api/admin/payments?days='+days).then(setPayments).catch(e=>setPaymentError(e.message));},[tab,days,data]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api.login({email,password});setPassword('');await load();}catch(e){setError((e as Error).message);setBusy(false);}}
 const users=(data?.users??[]).filter((u:any)=>u.email.toLowerCase().includes(q.toLowerCase())&&(!status||u.subscription_status===status));
 const trips=(data?.trips??[]).filter((t:any)=>(t.title+' '+t.email).toLowerCase().includes(q.toLowerCase()));
 function exportCsv(){const rows=tab==='Voyages'?trips:users;const keys=tab==='Voyages'?['id','title','email','created_at']:['id','email','subscription_status','subscription_plan','created_at','trips'];const cell=(x:unknown)=>'"'+String(x??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const csv=[keys,...rows.map((r:any)=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='mon-petit-voyageur-'+(tab==='Voyages'?'voyages':'utilisateurs')+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(!data)return <AdminLogin onLogin={async(email,password)=>{await api.login({email,password});setData(await get('/api/admin/dashboard?days='+days));}}/>;
 const clicks=data.metrics.filter((m:any)=>m.kind==='click').reduce((n:number,m:any)=>n+m.count,0);
 const views=data.metrics.filter((m:any)=>m.kind==='page_view').reduce((n:number,m:any)=>n+m.count,0);
 return <div className="admin-root live-admin"><aside className="admin-sidebar"><a className="admin-brand" href="https://www.monpetitvoyageur.com"><img className="admin-brand-logo" src="/logo.jpeg" alt="Mon Petit Voyageur" /><span><strong>Mon Petit Voyageur</strong><small>ADMINISTRATION</small></span></a><nav className="admin-nav">{tabs.map((t,i)=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setQ('');setStatus('');}}><b>{i+1}</b><span>{t}</span></button>)}</nav><button className="secondary" onClick={async()=>{await api.logout();setData(null);}}>Déconnexion</button></aside><main className="admin-main"><div className="admin-content"><div className="page-heading"><div><p className="eyebrow-admin">DONNÉES DE PRODUCTION</p><h1>{tab}</h1><p>Actualisé le {new Date(data.updated_at).toLocaleString('fr-FR')}</p></div><div className="heading-actions"><select aria-label="Période" value={days} onChange={e=>setDays(e.target.value)}><option value="7">7 derniers jours</option><option value="30">30 derniers jours</option><option value="365">365 derniers jours</option></select><button onClick={load} disabled={busy}>Actualiser</button></div></div><div className="admin-mobile-nav">{tabs.map(t=><button onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>
 {tab===tabs[0]&&<><section className="metric-grid">{[['Utilisateurs inscrits',data.totals.users],['Abonnements actifs',data.totals.active],['Voyages sauvegardés',data.totals.trips],['Nouveaux inscrits sur la période',data.totals.registrations]].map(([label,n])=><article className="metric-card" key={label}><p>{label}</p><div className="metric-value"><strong>{n}</strong></div></article>)}</section><section className="dashboard-grid"><article className="panel"><h2>Inscriptions sur la période</h2>{data.registrations.length?data.registrations.map((r:any)=><div key={r.day} className="admin-series"><span>{date(r.day)}</span><meter min="0" max={Math.max(...data.registrations.map((x:any)=>x.count),1)} value={r.count}/><strong>{r.count}</strong></div>):<p>Aucune inscription sur cette période.</p>}</article><article className="panel"><h2>À surveiller</h2><p>{data.totals.past_due} compte(s) avec paiement en retard.</p><p>{data.totals.trialing} essai(s) en cours.</p><p>{data.sources.stripe?'Stripe est configuré sur l’API.':'Stripe : connexion à l’API à terminer.'}</p><button className="secondary" onClick={()=>setTab('Connexions')}>État des connexions</button></article></section></>}
 {['Utilisateurs','Abonnements'].includes(tab)&&<section className="panel"><div className="admin-filters"><input aria-label="Rechercher un utilisateur" placeholder="Rechercher par email" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Statut" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les statuts</option>{Object.entries(statuses).slice(0,5).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={exportCsv}>Exporter les résultats</button></div><p>{users.length} utilisateur(s) affiché(s), sur {data.totals.users} au total. Maximum : {data.limits.users}.</p><div className="table-wrap"><table className="real-table"><thead><tr>{['Email','Statut','Offre','Échéance','Inscription','Voyages','Stripe'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{users.map((u:any)=><tr key={u.id}><td>{u.email}</td><td>{statuses[u.subscription_status]??u.subscription_status}</td><td>{u.subscription_plan||'—'}</td><td>{date(u.current_period_end)}</td><td>{date(u.created_at)}</td><td>{u.trips}</td><td>{u.stripe_customer_id?<a href={'https://dashboard.stripe.com/customers/'+encodeURIComponent(u.stripe_customer_id)} target="_blank" rel="noreferrer">Gérer dans Stripe ↗</a>:'Non lié'}</td></tr>)}</tbody></table>{!users.length&&<p>Aucun résultat.</p>}</div><p>Les statuts proviennent de la base du site, mise à jour par les notifications Stripe. Les modifications et résiliations se font dans Stripe.</p></section>}
 {tab==='Voyages'&&<section className="panel"><div className="admin-filters"><input aria-label="Rechercher un voyage" placeholder="Destination, titre ou email" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={exportCsv}>Exporter</button></div><p>{trips.length} voyage(s) affiché(s), maximum {data.limits.trips}.</p><div className="table-wrap"><table className="real-table"><thead><tr><th>Voyage</th><th>Utilisateur</th><th>Création</th><th>Modification</th></tr></thead><tbody>{trips.map((t:any)=><tr key={t.id}><td>{t.title}</td><td>{t.email}</td><td>{date(t.created_at)}</td><td>{date(t.updated_at)}</td></tr>)}</tbody></table>{!trips.length&&<p>Aucun voyage trouvé.</p>}</div></section>}
 {tab==='Clics & trafic'&&<section className="panel"><h2>{views} pages vues · {clicks} clics enregistrés</h2><p>Comptage depuis le {date(data.sources.tracking_since)}. Événements agrégés, sans identifiant visiteur ; il ne s’agit pas de visiteurs uniques. Les robots et bloqueurs peuvent affecter ces mesures.</p><table className="real-table"><thead><tr><th>Événement</th><th>Cible</th><th>Nombre</th></tr></thead><tbody>{data.metrics.map((m:any)=><tr key={m.kind+m.target}><td>{m.kind==='click'?'Clic':'Page vue'}</td><td>{{home:'Accueil',planner:'Création de voyage',booking:'Réservation',guide:'Guide',other_external:'Lien externe'}[m.target as string]||m.target}</td><td>{m.count}</td></tr>)}</tbody></table>{!data.metrics.length&&<p>Aucun événement enregistré sur cette période.</p>}</section>}
 {tab==='Revenus'&&<section className="panel"><h2>Factures Stripe</h2>{!data.sources.stripe?<p>Indisponible : la clé Stripe n’est pas configurée sur cette API. Aucun revenu estimé n’est affiché.</p>:paymentError?<p role="alert">{paymentError}</p>:!payments?<p>Chargement Stripe…</p>:<>{payments.test_mode&&<p className="admin-error">Mode test Stripe : ces factures ne sont pas des paiements réels.</p>}<p>Factures créées sur la période, jusqu’à 100 résultats.{payments.has_more?' Liste partielle : consultez Stripe pour la suite.':''}</p><div className="table-wrap"><table className="real-table"><thead><tr><th>Date</th><th>Client</th><th>Statut</th><th>Montant payé</th><th>Facture</th></tr></thead><tbody>{payments.invoices.map((i:any)=><tr key={i.id}><td>{new Date(i.created*1000).toLocaleDateString('fr-FR')}</td><td>{i.email||'—'}</td><td>{statuses[i.status]||i.status}</td><td>{money(i.amount,i.currency)}</td><td>{i.url&&<a href={i.url} target="_blank" rel="noreferrer">Ouvrir ↗</a>}</td></tr>)}</tbody></table></div>{!payments.invoices.length&&<p>Aucune facture sur cette période.</p>}</>}<a href="https://dashboard.stripe.com" target="_blank" rel="noreferrer">Ouvrir Stripe ↗</a></section>}
 {tab==='Connexions'&&<section className="panel"><h2>Sources des données</h2><p>Utilisateurs et voyages : {data.sources.database}.</p><p>Stripe API : {data.sources.stripe?'configurée':'non configurée'}.</p><p>Notifications Stripe : {data.sources.webhook?'clé de vérification configurée':'non configurées'}.</p><p>Clics et pages vues : comptage actif depuis le {date(data.sources.tracking_since)}.</p><p>Accès administrateur : réservé aux comptes autorisés côté serveur.</p><a href="https://dashboard.stripe.com" target="_blank" rel="noreferrer">Paramètres Stripe ↗</a></section>}
 <footer className="admin-footer">Mon Petit Voyageur · Administration sécurisée · Aucun chiffre de démonstration</footer></div></main></div>;
}
